# Generated by Django 5.0.1 on 2024-01-28 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pwweb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workrecord',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Denied', 'Denied'), ('Removed', 'Removed')], default='Pending', max_length=20),
        ),
    ]
